java:
  runtime:
    version: 11

spring:
  datasource:
    url: jdbc:h2:file:/data/carddb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: 'true'

springdoc:
  swagger-ui:
    path: /swagger-ui.html